name: Build server (prod)

on:
  push:
    branches:
      - master

jobs:
  convert-html:
    name: Convert Notebooks to HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build . --tag otevrenadatamfcr/opendata-stories
      - name: Login to DockerHub
        run: docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
      - name: Push to DockerHub
        run: docker push otevrenadatamfcr/opendata-stories